version: '3.8'

services:
  orquestrador-app:
    build: .
    env_file:
      - .env
    container_name: orquestrador_nest
    ports:
      - "3000:3000"
    depends_on:
      - redis_cache
    networks:
      - orquestrador_network
    restart: always

  redis_cache:
    image: redis:alpine
    container_name: orquestrador_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orquestrador_network
    restart: always

volumes:
  redis_data:
    driver: local

networks: 
  orquestrador_network:
    driver: bridge